name: Example 1

on: 
  push:
    branches: 
      - master
env:
  gh_pat: ${{secrets.GH_PAT}}
  test: ${{secrests.TES_SECRET}}
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lsb-release
        run: lsb_release -cs
        
      - name: Echo
        run: echo ${{env.test}}

      - name: Clone
        run: git clone https://${{env.gh_pat}}@github.com/Assetcues-Solutions-Private-Limited/AssetcuesWebApiAccessPanelServices.git

      - name: Verify
        run: ls -al AssetcuesWebApiAccessPanelServices
        
      - name: whoami
        run: whoami

