name: Example 1

on: 
  push:
    branches: 
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lsb-release
        run: lsb_release -cs

      - name: Clone
        run: git clone https://${{secrets.GH_PAT}}@github.com/Assetcues-Solutions-Private-Limited/AssetcuesWebApiAccessPanelServices.git

      - name: Verify
        run: ll AssetcuesWebApiAccessPanelServices
        
      - name: whoami
        run: whoami

