name: Example 1

on: 
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lsb-release
        run: lsb_release -cs

      - name: whoami
        run: whoami

      - name: mkdir
        run: mkdir /home/kadvait/test-folder
      
