name: Example 1

on: 
  push:
    branches: 
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lsb-release
        run: lsb_release -cs

      - name: Secret
        run: echo {{secrets.TES_SECRET}}

      - name: whoami
        run: whoami

      - name: mkdir
        run: mkdir /home/kadvait/test-folder
      
